import { TestDefinition } from "./test-types";

export const MOBILITY_TESTS: TestDefinition[] = [
  {
    key: "knee_to_wall",
    label: "Knee to Wall",
    groupe: "Cheville",
    unite: "cm",
    description: "Mesure la flexion dorsale de cheville.",
    protocole: "Genou en contact avec le mur, orteils reculés jusqu'à la distance maximale tout en gardant le talon au sol.",
    comparaisonCotes: true,
  },
  {
    key: "weight_bearing_lunge",
    label: "Weight Bearing Lunge",
    groupe: "Cheville",
    unite: "cm",
    description: "Mesure la flexion dorsale de cheville en charge.",
    protocole: "Fente avant, genou vers le mur, mesure de la distance orteil-mur maximale sans décoller le talon.",
    comparaisonCotes: true,
  },
  {
    key: "thomas_test",
    label: "Thomas Test",
    groupe: "Hanche",
    unite: "°",
    description: "Évalue la souplesse des fléchisseurs de hanche (psoas, droit fémoral).",
    protocole: "Allongé dos, une jambe fléchie contre la poitrine, mesure de l'angle de la cuisse opposée par rapport à la table.",
    comparaisonCotes: true,
  },
  {
    key: "ober_test",
    label: "Ober Test",
    groupe: "Hanche",
    unite: "°",
    description: "Évalue la tension de la bandelette ilio-tibiale.",
    protocole: "Décubitus latéral, hanche en extension/abduction relâchée, mesure de l'angle d'adduction passive.",
    comparaisonCotes: true,
  },
  {
    key: "straight_leg_raise",
    label: "Straight Leg Raise",
    groupe: "Hanche",
    unite: "°",
    description: "Évalue la souplesse des ischio-jambiers.",
    protocole: "Allongé dos, élévation jambe tendue jusqu'à la limite de flexion de hanche sans compensation lombaire.",
    comparaisonCotes: true,
  },
  {
    key: "hip_90_90",
    label: "90/90 (rotation interne/externe)",
    groupe: "Hanche",
    unite: "°",
    description: "Évalue l'amplitude de rotation interne et externe de hanche.",
    protocole: "Assis, hanche et genou fléchis à 90°, mesure de la rotation active maximale.",
    comparaisonCotes: true,
  },
  {
    key: "thoracic_rotation",
    label: "Rotation thoracique",
    groupe: "Thorax",
    unite: "°",
    description: "Évalue la mobilité en rotation du rachis thoracique.",
    protocole: "Position quadrupédique ou assise, rotation maximale du tronc, mesure de l'angle.",
    comparaisonCotes: true,
  },
  {
    key: "thoracic_extension",
    label: "Extension thoracique",
    groupe: "Thorax",
    unite: "cm",
    description: "Évalue la mobilité en extension du rachis thoracique.",
    protocole: "Test standardisé (ex : sur foam roller ou en position debout), mesure de l'amplitude atteinte.",
    comparaisonCotes: false,
  },
  {
    key: "shoulder_apley",
    label: "Apley Scratch Test",
    groupe: "Épaule",
    unite: "cm",
    description: "Évalue la mobilité combinée de l'épaule (rotation interne + externe).",
    protocole: "Mesure de la distance entre les mains dans le dos, une par-dessus l'épaule, l'autre par en dessous.",
    comparaisonCotes: true,
  },
  {
    key: "shoulder_flexion",
    label: "Flexion d'épaule",
    groupe: "Épaule",
    unite: "°",
    description: "Amplitude de flexion active/passive de l'épaule.",
    protocole: "Mesure goniométrique de la flexion maximale, bras tendu.",
    comparaisonCotes: true,
  },
  {
    key: "shoulder_rotation_ext",
    label: "Rotation externe d'épaule",
    groupe: "Épaule",
    unite: "°",
    description: "Amplitude de rotation externe, coude au corps.",
    protocole: "Coude fléchi à 90° au corps, mesure de la rotation externe maximale.",
    comparaisonCotes: true,
  },
  {
    key: "shoulder_rotation_int",
    label: "Rotation interne d'épaule",
    groupe: "Épaule",
    unite: "°",
    description: "Amplitude de rotation interne, coude au corps.",
    protocole: "Coude fléchi à 90° au corps, mesure de la rotation interne maximale.",
    comparaisonCotes: true,
  },
  {
    key: "wrist_mobility",
    label: "Mobilité du poignet",
    groupe: "Poignet",
    unite: "°",
    description: "Amplitude de flexion/extension du poignet.",
    protocole: "Mesure goniométrique en flexion et extension actives maximales.",
    comparaisonCotes: true,
  },
  {
    key: "knee_mobility",
    label: "Mobilité du genou",
    groupe: "Genou",
    unite: "°",
    description: "Amplitude de flexion du genou.",
    protocole: "Mesure goniométrique de la flexion active maximale, en décubitus ventral.",
    comparaisonCotes: true,
  },
];
