import { TestDefinition } from "./test-types";

export const PHYSICAL_TESTS: TestDefinition[] = [
  // Force
  {
    key: "1rm",
    label: "1RM",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale soulevée sur une répétition.",
    protocole: "Échauffement progressif puis tentatives successives jusqu'à la charge maximale sur une répétition technique.",
    comparaisonCotes: false,
  },
  {
    key: "3rm",
    label: "3RM",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale soulevée sur trois répétitions.",
    protocole: "Échauffement progressif puis tentatives jusqu'à la charge maximale sur 3 répétitions.",
    comparaisonCotes: false,
  },
  {
    key: "5rm",
    label: "5RM",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale soulevée sur cinq répétitions.",
    protocole: "Échauffement progressif puis tentatives jusqu'à la charge maximale sur 5 répétitions.",
    comparaisonCotes: false,
  },
  {
    key: "grip",
    label: "Force de préhension (Grip)",
    groupe: "Force",
    unite: "kg",
    description: "Force maximale de préhension manuelle.",
    protocole: "Dynamomètre de préhension, 2-3 essais par main, meilleur score conservé.",
    comparaisonCotes: true,
  },
  {
    key: "imtp",
    label: "IMTP (Isometric Mid-Thigh Pull)",
    groupe: "Force",
    unite: "N",
    description: "Force isométrique maximale en tirage mi-cuisse.",
    protocole: "Tirage isométrique maximal sur plateforme de force ou dynamomètre, barre à hauteur mi-cuisse.",
    comparaisonCotes: false,
  },
  {
    key: "squat_max",
    label: "Squat (charge max)",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale en squat.",
    protocole: "Test de charge maximale (1RM ou estimée) en squat, profondeur standardisée.",
    comparaisonCotes: false,
  },
  {
    key: "bench_max",
    label: "Développé couché (charge max)",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale en développé couché.",
    protocole: "Test de charge maximale (1RM ou estimée) en développé couché.",
    comparaisonCotes: false,
  },
  {
    key: "deadlift_max",
    label: "Soulevé de terre (charge max)",
    groupe: "Force",
    unite: "kg",
    description: "Charge maximale en soulevé de terre.",
    protocole: "Test de charge maximale (1RM ou estimée) en soulevé de terre.",
    comparaisonCotes: false,
  },

  // Puissance
  {
    key: "cmj",
    label: "CMJ (Counter Movement Jump)",
    groupe: "Puissance",
    unite: "cm",
    description: "Détente verticale avec contre-mouvement.",
    protocole: "Saut vertical maximal avec flexion préalable des jambes, mains sur les hanches. Mesure via tapis de contact ou plateforme.",
    comparaisonCotes: false,
  },
  {
    key: "sj",
    label: "SJ (Squat Jump)",
    groupe: "Puissance",
    unite: "cm",
    description: "Détente verticale sans contre-mouvement.",
    protocole: "Départ position squat maintenue 2-3 sec, saut vertical maximal sans contre-mouvement.",
    comparaisonCotes: false,
  },
  {
    key: "dj",
    label: "DJ (Drop Jump)",
    groupe: "Puissance",
    unite: "cm",
    description: "Saut en contrebas avec rebond, évalue la puissance réactive.",
    protocole: "Chute d'une hauteur standardisée puis rebond vertical maximal, temps de contact minimal.",
    comparaisonCotes: false,
  },
  {
    key: "rsi",
    label: "RSI (Reactive Strength Index)",
    groupe: "Puissance",
    unite: "index",
    description: "Ratio hauteur de saut / temps de contact au sol.",
    protocole: "Calculé automatiquement à partir du Drop Jump (hauteur de saut ÷ temps de contact).",
    comparaisonCotes: false,
  },

  // Vitesse
  {
    key: "sprint_5m",
    label: "Sprint 5m",
    groupe: "Vitesse",
    unite: "sec",
    description: "Temps sur 5 mètres départ arrêté.",
    protocole: "Cellules photoélectriques, départ arrêté, chronométrage sur 5m.",
    comparaisonCotes: false,
  },
  {
    key: "sprint_10m",
    label: "Sprint 10m",
    groupe: "Vitesse",
    unite: "sec",
    description: "Temps sur 10 mètres départ arrêté.",
    protocole: "Cellules photoélectriques, départ arrêté, chronométrage sur 10m.",
    comparaisonCotes: false,
  },
  {
    key: "sprint_20m",
    label: "Sprint 20m",
    groupe: "Vitesse",
    unite: "sec",
    description: "Temps sur 20 mètres départ arrêté.",
    protocole: "Cellules photoélectriques, départ arrêté, chronométrage sur 20m.",
    comparaisonCotes: false,
  },
  {
    key: "sprint_30m",
    label: "Sprint 30m",
    groupe: "Vitesse",
    unite: "sec",
    description: "Temps sur 30 mètres départ arrêté.",
    protocole: "Cellules photoélectriques, départ arrêté, chronométrage sur 30m.",
    comparaisonCotes: false,
  },
  {
    key: "flying_sprint",
    label: "Flying Sprint",
    groupe: "Vitesse",
    unite: "sec",
    description: "Vitesse maximale lancée sur une distance donnée.",
    protocole: "Zone d'élan puis chronométrage sur la distance test, départ lancé.",
    comparaisonCotes: false,
  },
  {
    key: "cod_505",
    label: "505 (Change of Direction)",
    groupe: "Vitesse",
    unite: "sec",
    description: "Capacité de changement de direction.",
    protocole: "Sprint 15m, demi-tour à 180° sur ligne, retour 5m chronométré.",
    comparaisonCotes: true,
  },
  {
    key: "illinois",
    label: "Illinois Test",
    groupe: "Vitesse",
    unite: "sec",
    description: "Agilité et changements de direction combinés.",
    protocole: "Parcours standardisé avec plots, chronométrage total du parcours.",
    comparaisonCotes: false,
  },
  {
    key: "t_test",
    label: "T-Test",
    groupe: "Vitesse",
    unite: "sec",
    description: "Agilité multidirectionnelle (avant/latéral/arrière).",
    protocole: "Parcours en T avec déplacements latéraux, chronométrage total.",
    comparaisonCotes: false,
  },

  // Endurance
  {
    key: "vma",
    label: "VMA",
    groupe: "Endurance",
    unite: "km/h",
    description: "Vitesse maximale aérobie.",
    protocole: "Test progressif (piste ou VAMEVAL) jusqu'à épuisement, dernier palier complété.",
    comparaisonCotes: false,
  },
  {
    key: "vameval",
    label: "VAMEVAL",
    groupe: "Endurance",
    unite: "km/h",
    description: "Test progressif d'évaluation de la VMA par paliers sonores.",
    protocole: "Paliers d'1 minute avec vitesse croissante, arrêt à épuisement.",
    comparaisonCotes: false,
  },
  {
    key: "yoyo",
    label: "Yo-Yo Intermittent Test",
    groupe: "Endurance",
    unite: "m",
    description: "Capacité à répéter des efforts intermittents à haute intensité.",
    protocole: "Navettes 20m avec récupération active, vitesse croissante par palier, distance totale parcourue.",
    comparaisonCotes: false,
  },
  {
    key: "luc_leger",
    label: "Luc Léger",
    groupe: "Endurance",
    unite: "palier",
    description: "Test navette progressif d'évaluation de la VO2max.",
    protocole: "Navettes 20m, vitesse croissante par palier d'1 minute, dernier palier atteint.",
    comparaisonCotes: false,
  },
  {
    key: "cooper",
    label: "Test de Cooper",
    groupe: "Endurance",
    unite: "m",
    description: "Distance parcourue en 12 minutes.",
    protocole: "Course continue de 12 minutes, distance totale mesurée.",
    comparaisonCotes: false,
  },
  {
    key: "vo2max",
    label: "VO2max",
    groupe: "Endurance",
    unite: "ml/kg/min",
    description: "Consommation maximale d'oxygène.",
    protocole: "Mesure directe (analyseur de gaz) ou estimée à partir d'un test progressif.",
    comparaisonCotes: false,
  },
  {
    key: "lactate",
    label: "Seuil lactique",
    groupe: "Endurance",
    unite: "mmol/L",
    description: "Concentration de lactate sanguin à un palier d'effort donné.",
    protocole: "Prélèvement capillaire à chaque palier d'un test progressif.",
    comparaisonCotes: false,
  },
];
